home/urls.py
from django.urls import path
from django.views.generic import TemplateView


urlpatterns = [
    path('contact-us/', TemplateView.as_view(template_name='home/user/contact_us.html'), name='contact_us_temp'),
]

properties/urls.py
from django.urls import path
from django.views.generic import TemplateView

from properties.views.user import (list_properties_view, create_property_view, 
                property_details_view, search_filter_list_properties, 
                list_propperty_category, latest_properties_carousel)
from properties.views.admin import create_property
from properties.ajax.property import get_latest_properties

urlpatterns = [
    #view
    path('',list_properties_view.ListPoppertiesUser.as_view(),name='user_list_properties'),
    path('<str:category>/',list_propperty_category.ListPoppertiesByCategory.as_view(),name='user_list_properties_category'),
    path('create/',create_property.CreatePropertyAdmin.as_view(),name='user_create_property'),
    path('details/<str:slug>/<str:uid>/',property_details_view.PropertyDetailsUser.as_view(),name='user_property_details'),

    #ajax
    path('ajax/list/filter/', search_filter_list_properties.SearchFilterPropertiesUser.as_view(), name='search_filter_properties'),
    path('ajax/list/latest-prop/', latest_properties_carousel.PropertyCarousel.as_view(), name='get_latest_prop_ajax'),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('home.urls')),
    path('superadmin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('properties/', include('properties.urls')),
    path('auth/', include('authentication.urls')),
    path('user/', include('user.urls')),
    path('notification/', include('notifications.urls')),
]


urlpatterns += static(settings.STATIC_URL,document_root=settings.STATICFILES_DIRS)

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.views.generic import TemplateView

from user.views.common import update_user_details
from user.ajax.user_ajax import fetch_user

urlpatterns = [
    # view
    path('update/details/', update_user_details.UpdateUserDetails.as_view(), name='update_user_details'),

    # ajax
    path('get-user/', fetch_user, name='fetch_user_ajax')
]

properties/models.py
from django.db import models
import uuid
import locale

from user.models import UserDetails


PROP_STATE = (
    ('deleted','Deleted'),
    ('active','Active'),
    ('suspented','Suspented'),
    ('draft','Draft'),
    ('sold','Sold'),
    ('pending','Pending'),
    ('cancel','Cancel'),
)

PROP_TYPE = (
    ('none','None'),
    ('rent','Rent'),
    ('lease','Lease'),
    ('sale','Sale'),
)

PROP_CATEG = (
    ('none','None'),
    ('apartment','Apartment'),
    ('villas','Villas'),
    ('commercial','Commercial'),
    ('office','Office'),
    ('flat','Flat'),
    ('house','House'),
    ('land','House'),
)

PROP_FRUN = (
    ('semi','Semi'),
    ('fully','Fully'),
    ('not','Not'),
)

PROP_AGE = (
    ('1','0-5'),
    ('2','0-10'),
    ('3','0-15'),
    ('4','0-20'),
    ('20+','20+'),
)


class PropertyImages(models.Model):
    uid = models.UUIDField(default=uuid.uuid4, unique=True)
    property = models.ForeignKey('Properties',on_delete=models.CASCADE, null=True, blank=True, related_name='property_img')
    image = models.ImageField(upload_to='properties/images/',null=True,blank=True)

    class Meta:
        verbose_name_plural = 'Property Images'
    
    def __str__(self):
        return str(self.uid)


class Properties(models.Model):
    uid = models.UUIDField(default=uuid.uuid4, unique=True)
    slug = models.CharField(max_length=250,unique=False,null=True,blank=True)
    user = models.ForeignKey(UserDetails, on_delete=models.CASCADE, null=True, blank=True)

    heading = models.CharField(max_length=250, unique=False, null=True, blank=True)
    description = models.TextField(null=True,blank=True)
    price = models.CharField(max_length=15, unique=False, blank=True, null=True)
      
    address = models.CharField(max_length=250, unique=False, blank=True, null=True)
    zipcode = models.CharField(max_length=20, unique=False, blank=True, null=True)
    place = models.CharField(max_length=100, unique=False, blank=True, null=True)
    city = models.CharField(max_length=100, unique=False, blank=True, null=True)
    state = models.CharField(max_length=100, unique=False, blank=True, null=True)

    building_age = models.CharField(max_length=20, default=1, choices=PROP_AGE, unique=False, blank=True, null=True)
    parking = models.IntegerField(default=0, unique=False, blank=True, null=True)

    rooms = models.CharField(default='1', max_length=20, unique=False, blank=True, null=True)
    bedroom = models.CharField(default='1', max_length=20, null=True, blank=True)
    bathroom = models.CharField(default='1', max_length=20, null=True, blank=True)
    area = models.FloatField(default=0.00, null=True, blank=True)

    type = models.CharField(max_length=100,unique=False,null=True,blank=True,choices=PROP_TYPE,default='none')
    category = models.CharField(max_length=100,unique=False,null=True,blank=True,choices=PROP_CATEG,default='none')
    furnished = models.CharField(max_length=100,unique=False,null=True,blank=True,choices=PROP_FRUN,default='not')
    status = models.CharField(max_length=100,unique=False,null=True,blank=True,choices=PROP_STATE,default='active')

    contact_name = models.CharField(max_length=100, unique=False, blank=True, null=True)
    contact_email = models.EmailField(max_length=100, unique=False, blank=True, null=True)
    contact_phone = models.CharField(max_length=20, unique=False, blank=True, null=True)

    floor_plan = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.slug = str(self.heading).lower().replace(' ','-')
        super(Properties,self).save(*args,**kwargs)

    class Meta:
        verbose_name_plural = 'Properties'

    def __str__(self):
        return str(self.heading)

    @property
    def currency(self):
        locale.setlocale(locale.LC_MONETARY, 'en_IN')
        price = locale.currency(float(self.price.replace(',','')), grouping=True)
        return price
    
    @property
    def currency_with_no_symb(self):
        locale.setlocale(locale.LC_MONETARY, 'en_IN')
        price = locale.currency(float(self.price.replace(',','')), grouping=True,symbol=False)
        return price

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import post_save
from django.dispatch import receiver

import uuid


class Users(AbstractUser):
    uid = models.UUIDField(unique=True, default=uuid.uuid4)
    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(_('username'), max_length=50, null=True, blank=True, unique=True)
    name = models.CharField(max_length=100, unique=False, null=True, blank=True)
    password = models.CharField(_('password'), max_length=50, null=True, blank=True, unique=True)

    class Meta:
        verbose_name_plural = "Users"

    def __str__(self):
        return str(self.email)


@receiver(post_save,sender=Users)
def generate_user_details(sender,instance=None,created=False,**kwargs):
    if created:
        UserDetails.objects.create(email=instance.email, full_name=instance.name, 
        first_name=instance.name.split(' ')[0], last_name=instance.name.split(' ')[1:])
    else:
        pass


class UserDetails(models.Model):
    uid = models.UUIDField(default=uuid.uuid4, unique=True)
    user = models.ForeignKey(Users, on_delete=models.CASCADE, null=True, blank=True, related_name='user_dtl')
    first_name = models.CharField(max_length=100, unique=False, null=True, blank=True)
    last_name = models.CharField(max_length=100, unique=False, null=True, blank=True)
    full_name = models.CharField(max_length=100, unique=False, null=True, blank=True)
    email = models.EmailField(unique=True, null=True, blank=True)

    address =  models.TextField(max_length=250, null=True, blank=True)
    place =  models.CharField(max_length=100, unique=False, null=True, blank=True)
    city =  models.CharField(max_length=100, unique=False, null=True, blank=True)
    state =  models.CharField(max_length=100, unique=False, null=True, blank=True)
    zipcode =  models.CharField(max_length=100, unique=False, null=True, blank=True)
    
    phone =  models.CharField(max_length=100, unique=False, null=True, blank=True)
    alternative_phone =  models.CharField(max_length=100, unique=False, null=True, blank=True)
    
    alternative_email =  models.CharField(max_length=100, unique=False, null=True, blank=True)
    alternative_contact_person = models.CharField(max_length=100, unique=False, null=True, blank=True)

    job_profile = models.CharField(max_length=100, unique=False, null=True, blank=True)
    job_role = models.CharField(max_length=100, unique=False, null=True, blank=True)

    about = models.TextField(max_length=500, null=True, blank=True)

    join_date = models.DateTimeField(auto_now_add=True)

    role = models.CharField(null=True, blank=True, max_length=50)


    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name_plural = 'User Details'

    def save(self, *args, **kwargs):
        self.full_name = f"{self.first_name} {self.last_name}"
        self.role = 'admin' if self.user.is_superuser == True else 'user'
        super(UserDetails,self).save(*args,**kwargs)


class UserProfileDetails(models.Model):
    uid = models.UUIDField(default=uuid.uuid4,unique=True)
    user = models.ForeignKey(UserDetails, on_delete=models.CASCADE, null=True, blank=True, related_name='user_profile_img')
    profile_image = models.ImageField(upload_to='user/profile/profile-image/', null=True, blank=True)

    def __str__(self):
        return self.user.full_name

    class Meta:
        verbose_name_plural = 'User Profile Details'

    
class GuestUsers(models.Model):
    uid = models.UUIDField(default=uuid.uuid4, unique=True)
    email = models.EmailField(null=True, blank=True, max_length=100, unique=False)
    full_name = models.CharField(max_length=100, unique=False, null=True, blank=True)
    phone = models.CharField(max_length=20, unique=False, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Guest Users'

    def __str__(self):
        return self.full_name

properties/templates/properties/user/create_property.html
{% extends 'master/master.html' %}
{% block content %}
{% include 'properties/user/create_property_form.html' %}
{% endblock %}

properties/templates/properties/user/list_properties.html
{% load humanize %}
{% for property in object_list %}
<div class="col-lg-4 col-md-6 col-sm-12">
    <div class="property-listing property-2">

        <div class="listing-img-wrapper">
            <div class="list-img-slide">
                <div class="click">
                    {% for image in property.property_img.all %}

                    <div><a href="{% url 'user_property_details' property.slug property.uid %}"><img
                                src="{{image.image.url}}" alt="{{image.uid}}" class="img-fluid mx-auto" /></a></div>

                    {% endfor %}
                </div>
            </div>
            <span class="property-type">For {{property.type.capitalize}}</span>
        </div>

        <div class="listing-detail-wrapper pb-0">
            <div class="listing-short-detail">
                <h4 class="listing-name"><a
                        href="{% url 'user_property_details' property.slug property.uid %}">{{property.heading}}</a>
                </h4>
            </div>
        </div>

        <div class="price-features-wrapper">
            <div class="listing-price-fx">
                <h6 class="listing-card-info-price">{{property.currency}}</h6>
            </div>
            <div class="list-fx-features">
                <div class="listing-card-info-icon">
                    <span class="inc-fleat inc-bed">{{property.bedroom}} Beds</span>
                </div>
                <div class="listing-card-info-icon">
                    <span class="inc-fleat inc-bath">{{property.bathroom}} Bath</span>
                </div>
            </div>
        </div>

    </div>
</div>
{% endfor %}

properties/templates/properties/user/list_properties_template.html
{% extends 'master/master.html' %}
{% block content %}
{% include 'common/search_bar.html' %}
<section id="lstPrp" class="p-40">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 d-flex">
                <h4>Total Property Find is: <span class="theme-cl">{{object_list.count}}</span></h4>
            </div>
        </div>

        <div class="row">
            {% include 'properties/user/list_properties.html' %}
        </div>
        {% include 'properties/common/pagination.html' with url_name=request.resolver_match.view_name %}
    </div>
</section>

{% endblock %}

properties/templates/properties/user/property_carousel.html
{% load humanize %}

<div class="col-lg-12 col-md-12">
    <div class="property-slide">
        {% for property in properties %}
        <div class="col-lg-3 col-md-3 col-sm-12">
            <div class="property-listing property-2">

                <div class="listing-img-wrapper">
                    <div class="list-img-slide">
                        <div class="click">
                            {% for image in property.property_img.all %}

                            <div><a href="{% url 'user_property_details' property.slug property.uid %}"><img
                                        src="{{image.image.url}}" alt="{{image.uid}}"
                                        class="img-fluid mx-auto" /></a></div>

                            {% endfor %}
                        </div>
                    </div>
                    <span class="property-type">For {{property.type.capitalize}}</span>
                </div>

                <div class="listing-detail-wrapper pb-0">
                    <div class="listing-short-detail">
                        <h4 class="listing-name"><a
                                href="{% url 'user_property_details' property.slug property.uid %}">{{property.heading}}</a>
                        </h4>
                    </div>
                </div>

                <div class="price-features-wrapper">
                    <div class="listing-price-fx">
                        <h6 class="listing-card-info-price">{{property.currency}}</h6>
                    </div>
                    <div class="list-fx-features">
                        <div class="listing-card-info-icon">
                            <span class="inc-fleat inc-bed">{{property.bedroom}} Beds</span>
                        </div>
                        <div class="listing-card-info-icon">
                            <span class="inc-fleat inc-bath">{{property.bathroom}} Bath</span>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        {% endfor %}
    </div>
</div>

properties/templates/properties/user/property_details.html
{% extends 'master/master.html' %}
{% block content %}

<section class="gray">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12 col-sm-12">

                <div class="slide-property-first mb-4">
                    <div class="pr-price-into">
                        <h2>{{property.heading}}<span class="prt-type {% if property.type == 'rent' %} rent {% elif property.type == 'sale' %}sale{% endif %}">For {{property.type}}</span></h2>
                        <span><i class="ti-location-pin"></i>{{property.place}}, {{property.city}}</span>
                    </div>
                </div>

                <div class="property3-slide single-advance-property mb-4">

                    <div class="slider-for">
                        {% for image in property.property_img.all %}
                        <a href="assets/img/p-1.jpg" class="item-slick"><img src="{{image.image.url}}" alt="Alt"></a>
                        {% endfor %}
                    </div>
                    <div class="slider-nav">
                        {% for image in property.property_img.all %}
                        <div class="item-slick"><img src="{{image.image.url}}" alt="Alt"></div>
                        {% endfor %}
                    </div>

                </div>

                <div class="block-wrap">

                    <div class="block-header">
                        <h4 class="block-title">Property Info</h4>
                    </div>

                    <div class="block-body">
                        <ul class="dw-proprty-info">
                            <li class="text-capitalize"><strong>Bedrooms</strong>{{property.bedroom}} bedroom</li>
                            <li class="text-capitalize"><strong>Total Rooms</strong>{{property.rooms}} rooms</li>
                            <li class="text-capitalize"><strong>Parking</strong>{{property.parking}} cars</li>
                            <li class="text-capitalize"><strong>Area</strong>{{property.area}} sq.ft</li>
                            <li class="text-capitalize"><strong>Type</strong>{{property.type}}</li>
                            <li class="text-capitalize"><strong>Price</strong>{{property.currency}}</li>
                            <li class="text-capitalize"><strong>City</strong>{{property.city}}</li>
                            <li class="text-capitalize"><strong>Build On</strong>{{property.get_building_age_display}} Years</li>
                        </ul>
                    </div>

                </div>

                <div class="block-wrap">

                    <div class="block-header">
                        <h4 class="block-title">Description</h4>
                    </div>

                    <div class="block-body">
                        <p>{{property.description | safe}}</p>
                    </div>

                </div>
                {% if property.floor_plan %}
                <div class="block-wrap">

                    <div class="block-header">
                        <h4 class="block-title">Floor Plan</h4>
                    </div>

                    <div class="block-body">
                        <div class="accordion" id="floor-option">
                            <div class="card">
                                <div class="card-header" id="firstFloor">
                                    <h2 class="mb-0">
                                        <button type="button" class="btn btn-link" data-toggle="collapse"
                                            data-target="#firstfloor">First Floor<span>740 sq ft</span></button>
                                    </h2>
                                </div>
                                <div id="firstfloor" class="collapse show" aria-labelledby="firstFloor"
                                    data-parent="#floor-option">
                                    <div class="card-body">
                                        <img src="assets/img/floor.jpg" class="img-fluid" alt="" />
                                    </div>
                                </div>
                            </div>
                            <div class="card">
                                <div class="card-header" id="seconfFloor">
                                    <h2 class="mb-0">
                                        <button type="button" class="btn btn-link collapsed" data-toggle="collapse"
                                            data-target="#secondfloor">Second Floor<span>710 sq ft</span></button>
                                    </h2>
                                </div>
                                <div id="secondfloor" class="collapse" aria-labelledby="seconfFloor"
                                    data-parent="#floor-option">
                                    <div class="card-body">
                                        <img src="assets/img/floor.jpg" class="img-fluid" alt="" />
                                    </div>
                                </div>
                            </div>
                            <div class="card">
                                <div class="card-header" id="third-garage">
                                    <h2 class="mb-0">
                                        <button type="button" class="btn btn-link collapsed" data-toggle="collapse"
                                            data-target="#garages">Garage<span>520 sq ft</span></button>
                                    </h2>
                                </div>
                                <div id="garages" class="collapse" aria-labelledby="third-garage"
                                    data-parent="#floor-option">
                                    <div class="card-body">
                                        <img src="assets/img/floor.jpg" class="img-fluid" alt="" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                {% endif %}
            </div>
            <div class="col-lg-4 col-md-12 col-sm-12">
                {% include 'properties/user/property_details_query_form.html' %}
            </div>

        </div>
    </div>
</section>
{% endblock %}

properties/templates/properties/user/property_details_query_form.html
{% load static %}
<div class="page-sidebar">

    <div class="slide-property-sec mb-4">
        <div class="pr-all-info">

            <div class="pr-single-info">
                <a href="JavaScript:Void(0);" data-toggle="tooltip" data-original-title="Get Print"><i
                        class="ti-printer"></i></a>
            </div>

            <div class="pr-single-info">
                <a href="JavaScript:Void(0);" class="compare-button" data-toggle="tooltip"
                    data-original-title="Compare"><i class="ti-control-shuffle"></i></a>
            </div>

            <div class="pr-single-info">
                <a href="JavaScript:Void(0);" class="like-bitt add-to-favorite" data-toggle="tooltip"
                    data-original-title="Add To Favorites"><i class="far fa-heart"></i></a>
            </div>

        </div>
    </div>

    <div class="agent-widget">
        <div class="agent-title">
            <div class="agent-photo">
                {% for image in property.user.user_profile_img.filter %}
                <img src="{{image.profile_image.url}}" alt="">
                {% endfor %}
            </div>
            <div class="agent-details">
                <h4><a href="#">{{property.user.full_name}}</a></h4>
                <span class="d-flex"><i class="fas fa-mobile-alt"></i>{{property.user.phone}}</span>
            </div>
            <div class="clearfix"></div>
        </div>
        <form action="{% url 'send_message_user' %}" method="post" id="sndmsgFrm" data-prop-id="{{property.uid}}">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Your Full Name" name="full_name">
            </div>
            <div class="form-group">
                <input type="email" class="form-control" placeholder="Your Email" name="email">
            </div>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Your Phone" name="phone">
            </div>
            <div class="form-group">
                <textarea class="form-control" placeholder="Your Message" name="comment"></textarea>
            </div>
        </form>
        <a href="#" class="btn btn-theme full-width" id="sndmsg">Send Message</a>
    </div>

</div>